### PR TITLE
fix auto-color-off code

### LINKED ISSUE #69: using color (or not) depending on `-t 1` seems wrong
https://github.com/kvz/bash3boilerplate/blob/9b739b4cf0c0c9f5454f7889e2417b258b1072dc/main.sh#L78

The line

```
if [ "${NO_COLOR}" = "true" ] || [[ "${TERM:-}" != "xterm"* ]] || [ -t 1 ]; then
```

seems to be wrong really in at least 2 different ways.

1) It checks STDOUT to be connected to a terminal while logging happens on STDERR only.
2) It turns OFF colors if STDOUT is actually connected to a terminal.

I'm guessing here but a quick check seems to suggest that nobody noticed until now because `__b3bp_log` always got called in a subshell which actually was not connected to a terminal. If the function would be just called - as suggested by shellcheck - the code would not work as expected.

Now I can fix that, but before that I wanted to ask if there is something about this code, or the decisions leading to this code, which I overlooked or I don't understand.

### PR DESCRIPTION
**Pull request by mstreuhofer**
turn off colors if NO_COLOR is "true" or TERM is not "xterm*" or STDERR
is not connected to a terminal, but ignore TERM and STDERR if NO_COLOR
is set to "false" explicitly.

Fixes #69

### CODE REVIEW

File: main.sh [hunk 1]
```diff
@@ -75,7 +75,7 @@ function __b3bp_log () {
   local color="${!colorvar:-$color_error}"
   local color_reset="\x1b[0m"
 
-  if [ "${NO_COLOR}" = "true" ] || [[ "${TERM:-}" != "xterm"* ]] || [ -t 1 ]; then
+  if [ "${NO_COLOR:-}" = "true" ] || ([ "${NO_COLOR:-}" != "false" ] && ([[ "${TERM:-}" != "xterm"* ]] || [ ! -t 2 ])); then
```
Comment (zbeekman) [inline main.sh]: The logic here is getting complex... might it be time for `if ; then; else; fi`?

Comment (mstreuhofer) [inline main.sh]: that's what i did first but opted for the complex line for the delete-key-friendliness.
but if you see it too then i'll change it to a separate `if`.

File: main.sh [hunk 2]
```diff
@@ -75,9 +75,11 @@ function __b3bp_log () {
   local color="${!colorvar:-$color_error}"
   local color_reset="\x1b[0m"
 
-  if [ "${NO_COLOR}" = "true" ] || [[ "${TERM:-}" != "xterm"* ]] || [ -t 1 ]; then
-    # Don't use colors on pipes or non-recognized terminals
-    color=""; color_reset=""
+  if [ "${NO_COLOR}" = "true" ] || [[ "${TERM:-}" != "xterm"* ]] || [ ! -t 2 ]; then
```
Comment (kvz) [inline main.sh]: I think this `NO_COLOR ` needs to an `:-` also?

**Comment by kvz** [comment]
Thanks for this! Added just a minor thing

File: main.sh (hunk 2 above)
Comment (mstreuhofer) [inline main.sh]: you're right. one `:-` coming up.

**Comment by mstreuhofer** [comment]
anything else holding this PR from being merged?

**Comment by zbeekman** [comment]
@kvz Hope you don't mind my taking the initiative to merge this.

**Comment by kvz** [comment]
That's fine, I do notice a build fail on master after merging this one tho https://travis-ci.org/kvz/bash3boilerplate/builds/181415318

**Comment by zbeekman** [comment]
@kvz Yes it's complaining about outdated NPM packages... I guess these are related to the acceptance testing? Can they just be updated?

**Comment by zbeekman** [comment]
OK, I'm an NPM/Node/JS noob, but my suspicion is that this has to do with Travis-CI caching. I'm going to investigate and if my hunch is confirmed, I'll delete the cache and re-run

**Comment by kvz** [comment]
Seems it worked this time :) thanks!

**Comment by zbeekman** [comment]
@kvz There are a lot of NPM warnings/errors about deprecated packages, see, e.g., https://travis-ci.org/kvz/bash3boilerplate/jobs/181415319#L197 I have no idea how to resolve those... but that is where the job failed in the past, so it might be wise to try to address them.

**Comment by zbeekman** [comment]
Also, I'm not sure what the status of the bugs noted in the `.travis.yml` file are, but perhaps upgrading some packages will make them go away, obviating the work arounds...

**Comment by kvz** [comment]
> There are a lot of NPM warnings/errors about deprecated packages, see, e.g., https://travis-ci.org/kvz/bash3boilerplate/jobs/181415319#L197 I have no idea how to resolve those... but that is where the job failed in the past, so it might be wise to try to address them.

Handling in https://github.com/kvz/bash3boilerplate/issues/75
